// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Roxosoft.DAL;
using System;

namespace Roxosoft.DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20180506155554_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Roxosoft.Common.Models.CartModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ProductCount");

                    b.Property<Guid>("ProductUid");

                    b.HasKey("Id");

                    b.HasIndex("ProductUid");

                    b.ToTable("Cart");
                });

            modelBuilder.Entity("Roxosoft.Common.Models.OrderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<Guid?>("CreateUserUid");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<int>("Status");

                    b.Property<int>("TotalCount");

                    b.Property<decimal>("TotalPrice");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<Guid?>("UpdateUserUid");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Roxosoft.Common.Models.ProductModel", b =>
                {
                    b.Property<Guid>("Uid")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreateDate");

                    b.Property<Guid?>("CreateUserUid");

                    b.Property<string>("Description");

                    b.Property<bool>("IsActive");

                    b.Property<string>("Name");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("UpdateDate");

                    b.Property<Guid?>("UpdateUserUid");

                    b.HasKey("Uid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Roxosoft.Common.Models.ProductsInOrders", b =>
                {
                    b.Property<Guid>("ProductUid");

                    b.Property<int>("OrderId");

                    b.Property<int>("ProductCount");

                    b.HasKey("ProductUid", "OrderId");

                    b.HasIndex("OrderId");

                    b.ToTable("ProductsInOrders");
                });

            modelBuilder.Entity("Roxosoft.Common.Models.CartModel", b =>
                {
                    b.HasOne("Roxosoft.Common.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductUid")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Roxosoft.Common.Models.ProductsInOrders", b =>
                {
                    b.HasOne("Roxosoft.Common.Models.OrderModel", "Order")
                        .WithMany("ProductsInOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Roxosoft.Common.Models.ProductModel", "Product")
                        .WithMany()
                        .HasForeignKey("ProductUid")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
